apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: precious-quail-nodejs 
  janus-idp.io/tekton: precious-quail-nodejs
  backstage.io/kubernetes-id: precious-quail-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: precious-quail-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  